FROM python:3.11

WORKDIR /api

COPY ./api/requirements.txt /api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

COPY ./api/main.py /api/main.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
