FROM python:3.11

WORKDIR /restaurant-location-service

COPY ./api/requirements.txt /restaurant-location-service/api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /restaurant-location-service/api/requirements.txt

COPY ./api /restaurant-location-service/api

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "80"]
