FROM python:3.11

WORKDIR /pin-service

COPY ./api/requirements.txt /pin-service/api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /pin-service/api/requirements.txt

COPY ./api /pin-service/api

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "80"]
